### ISSUE TITLE
verify_event_token doesn't need to do padding before doing jwt decode

### ISSUE THREAD

**Issue by shashankkr9** [flockchat/pyflock#1]

**Comment by Balajiganapathi** [comment]
Fixed. The padding is being done because flock does urlsafe base64 encode while jwt library needs standard base64.

**Comment by shashankkr9** [comment]
verify_event_token was failing for query parameter tokens at bot configuration page and sidebar. I had a consistent repro at least for these cases. You might want to relook if verify_event_token is also meant to for the above use cases. 

We can use a try catch to attempt decode without padding as well to cover all cases. Thoughts?

**Comment by Balajiganapathi** [comment]
Actually I rechecked the docs, padding is not required. I had added that logic in trying to solve some other problem. I have removed the padding code now and directly calling the underlying jwt library. 

verify_event_token is only meant for use on the token received in "X-FLOCK-EVENT-TOKEN" header received at the event url code in the server.
